name="single-window-session"
dir="~/Desktop"

[[windows]]
name="window-one"
dir="~/dev"

[[windows]]
dir="~/dev/bloom"

  [[windows.panes]]
  [[windows.panes]]
    dir="~/dev/bloom/dashboard"

[[windows]]