name="single-window-session"
dir="~/Desktop"

[[windows]]
name="window-one"
dir="~/dev"

[[windows]]
dir="~/dev/project"

  [[windows.panes]]
  [[windows.panes]]
    dir="~/dev/project/src"

[[windows]]