name = "tmuxctl_test"
dir = "~/dev/bloom"

# window to start on
window = "hub"

[[windows]]
  name="docker"
  dir="~/dev/bloom/dashboard-docker"
  layout="tiled"

  [[windows.panes]]
    dir="~/dev/bloom/fb_scraper"

[[windows]]
  name="hub"
  dir="~/dev/bloom/bloom-hub"
  layout="main-horizontal"

  [[windows.panes]]
  [[windows.panes]]
    dir="~/dev/bloom/bloom-hub/apps/api"
  [[windows.panes]]
    dir="~/dev/bloom/bloom-hub/apps/app"

[[windows]]
  name="dashboard"
  dir="~/dev/bloom/dashboard"

  [[windows.panes]]
  [[windows.panes]]
    dir="~/dev/bloom/dashboard/scripts"

[[windows]]
  name="ssh"