name = "tmuxctl_test"
dir = "~/dev/bloom"

# selects the window to start in
select-window = "hub" 
# selects the pane to start in.
# must select a window  first, otherwise ignored
# first panel is 1 and so on...
select-pane = 3

[[windows]]
  name="docker"
  dir="~/dev/bloom/dashboard-docker"
  layout="tiled"
  sync=true

  [[windows.panes]]
    dir="~/dev/bloom/fb_scraper"
    zoom=true
  [[windows.panes]]
  [[windows.panes]]

[[windows]]
  name="hub"
  dir="~/dev/bloom/bloom-hub"
  layout="main-horizontal"

  [[windows.panes]]
  [[windows.panes]]
    dir="~/dev/bloom/bloom-hub/apps/api"
  [[windows.panes]]
    dir="~/dev/bloom/bloom-hub/apps/app"

[[windows]]
  name="dashboard"
  dir="~/dev/bloom/dashboard"

  [[windows.panes]]
  [[windows.panes]]
    dir="~/dev/bloom/dashboard/scripts"

[[windows]]
  name="ssh"