name = "test"
dir = "/Users/alx0u/dev/bloom"

[[windows]]
  name="docker"
  dir="/Users/alx0u/dev/bloom/dashboard-docker"
  layout="tiled"

  [[windows.panes]]
  [[windows.panes]]

[[windows]]
  name="hub"
  dir="/Users/alx0u/dev/bloom/bloom-hub"
  layout="main-horizontal"

  [[windows.panes]]
  [[windows.panes]]
    dir="/Users/alx0u/dev/bloom/bloom-hub/apps/api"
  [[windows.panes]]
    dir="/Users/alx0u/dev/bloom/bloom-hub/apps/app"

[[windows]]
  name="dashboard"
  dir="/Users/alx0u/dev/bloom/dashboard"

[[windows]]
  name="ssh"
  dir="/Users/alx0u/dev/bloom"